import { defineConfig, test, request, expect } from '@playwright/test';
import { timeStamp } from 'console';

// test.only('login page with failing assertion', async ({ page }) => { - run only this test -> test.only
const endpoint = "https://restful-booker.herokuapp.com";


test.describe('grupa testow api', () => {

    let respObj: any = undefined;

    test.beforeAll(async ({ request }) => {
        const auth = await request.post(`${endpoint}/auth`, {
            data: {
                "username": process.env.USER_NAME,
                "password": process.env.PASSWORD
            }
        });
        respObj = await auth.json();
        console.log(respObj.token);
    });

    test.only('simple Api test', async ({ request }) => {
        // Arrange
        const updateBooking = await request.put(`${endpoint}/booking/1`, { // hardcoded booking id
            headers: {
                // "Authorization": respObj.token,
                "Cookie": `token=${respObj.token}`
            },
            data: {
                "firstname": "James",
                "lastname": "Brown",
                "totalprice": 111,
                "depositpaid": true,
                "bookingdates": {
                    "checkin": "2018-01-01",
                    "checkout": "2019-01-01"
                },
                "additionalneeds": `Breakfast and some edited stuff + ${timeStamp}`
            }
        });

        const respObjBooking = await updateBooking.json();
        console.log(respObjBooking);

        expect(updateBooking.status()).toBe(200);
        expect(respObjBooking.firstname).toBe("James")

    });

    // below tests were generated by Windsurf AI agent within few seconds
    test('GetBookingIds - All bookings', async ({ request }) => {
        // Arrange
        const getBookingIds = await request.get(`${endpoint}/booking`);

        // Act
        const bookingIds = await getBookingIds.json();
        console.log('Booking IDs:', bookingIds);

        // Assert
        expect(getBookingIds.status()).toBe(200);
        expect(Array.isArray(bookingIds)).toBe(true);
        
        // Verify each booking has an ID
        if (bookingIds.length > 0) {
            expect(bookingIds[0]).toHaveProperty('bookingid');
            expect(typeof bookingIds[0].bookingid).toBe('number');
        }
    });

    test('GetBookingIds - Filter by firstname', async ({ request }) => {
        // Arrange
        const firstname = 'Sally';
        const getBookingIds = await request.get(`${endpoint}/booking`, {
            params: { firstname }
        });

        // Act
        const bookingIds = await getBookingIds.json();
        console.log(`Booking IDs for firstname '${firstname}':`, bookingIds);

        // Assert
        expect(getBookingIds.status()).toBe(200);
        expect(Array.isArray(bookingIds)).toBe(true);
    });

    test('GetBookingIds - Filter by checkin date', async ({ request }) => {
        // Arrange
        const checkin = '2013-02-23';
        const getBookingIds = await request.get(`${endpoint}/booking`, {
            params: { checkin }
        });

        // Act
        const bookingIds = await getBookingIds.json();
        console.log(`Booking IDs with checkin >= '${checkin}':`, bookingIds);

        // Assert
        expect(getBookingIds.status()).toBe(200);
        expect(Array.isArray(bookingIds)).toBe(true);
    });
    
})