
// userPage.test.js
import { test, expect } from '@playwright/test';
import { LoginPage, UserPage } from '../test-data/userPage-testcraft.page';

test.describe('Username Input Field Tests', () => {
    // These tests was generated by Craft AI, 
    // an AI-powered test generation tool that creates tests based on user interactions and application behavior. 
    // The tests are designed to validate the functionality of the username input field on the login page of the application.
    // Both required updates to the UserPage class and the test cases themselves, as the generated code contained some errors
    //  and inconsistencies that needed to be addressed for the tests to run successfully.
    // But it was configuration issue on my side - it is possible to select TS as a programing language
    let userPage: UserPage;

    test.beforeEach(async ({ page }) => {
        userPage = new UserPage(page);
        await page.goto('https://www.saucedemo.com/');
    });

    test('Verify that the input field accepts a valid username with a mix of letters and numbers', async ({ page }) => {
        const validUserName = 'standard_user'; 
        await userPage.enterUsername(validUserName);
        const value = await page.inputValue(userPage.usernameInput);
        expect(value).toBe(validUserName);
    });

    test('Check if the placeholder text "Username" is displayed correctly when the input field is empty', async () => {
        const placeholderText = await userPage.getPlaceholder();
        expect(placeholderText).toBe('Username');
    });
});

const baseUrl = 'https://www.saucedemo.com/';

test.describe('Login Tests', () => {
    //these tests were generated by Craft AI, an AI-powered test generation tool that creates tests based on user interactions and application behavior.
    // Mostly without additional
    let loginPage: LoginPage;

    test.beforeEach(async ({ page }) => {
        loginPage = new LoginPage(page);
        await page.goto(baseUrl);
    });

    test('should display error message for invalid credentials', async () => {
        await loginPage.enterUsername('invalid_user');
        await loginPage.enterPassword('invalid_password');
        await loginPage.clickLoginButton();
        
        const errorMessage = await loginPage.getErrorMessageText();
        expect(errorMessage).toContain('Epic sadface: Username and password do not match any user in this service');
    });

    test('should not display error message for valid credentials', async () => {
        await loginPage.enterUsername('standard_user');
        await loginPage.enterPassword('secret_sauce');
        await loginPage.clickLoginButton();

        const errorMessage = await loginPage.getErrorMessageText();
        expect(errorMessage).toBeNull();
    });

    test('should require username', async () => {
        await loginPage.enterPassword('secret_sauce');
        await loginPage.clickLoginButton();

        const errorMessage = await loginPage.getErrorMessageText();
        expect(errorMessage).toContain('Epic sadface: Username is required');
    });

    test('should require password', async () => {
        await loginPage.enterUsername('standard_user');
        await loginPage.clickLoginButton();

        const errorMessage = await loginPage.getErrorMessageText();
        expect(errorMessage).toContain('Epic sadface: Password is required');
    });

    test('should allow login with valid credentials', async ({ page }) => {
        await loginPage.enterUsername('standard_user');
        await loginPage.enterPassword('secret_sauce');
        await loginPage.clickLoginButton();

        await expect(page).toHaveURL(/inventory/);
    });
});